# BatchFileRenamer v4
# Windows PowerShell + WinForms. No Python required.

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()

$script:Lang = 'ZH'
$script:Theme = 'Dark'
$script:Rules = New-Object System.Collections.Generic.List[object]
$script:Sources = New-Object System.Collections.Generic.List[string]

$FontTitle = New-Object System.Drawing.Font('Segoe UI', 16, [System.Drawing.FontStyle]::Bold)
$FontSub = New-Object System.Drawing.Font('Segoe UI', 9)
$FontNormal = New-Object System.Drawing.Font('Segoe UI', 10)
$FontButton = New-Object System.Drawing.Font('Segoe UI', 9, [System.Drawing.FontStyle]::Bold)
$FontMono = New-Object System.Drawing.Font('Consolas', 9)

function Set-Colors {
    if ($script:Theme -eq 'Light') {
        $script:Cbg=[System.Drawing.Color]::FromArgb(247,250,252); $script:Ccard=[System.Drawing.Color]::White
        $script:Ccard2=[System.Drawing.Color]::FromArgb(235,241,248); $script:Ctext=[System.Drawing.Color]::FromArgb(15,23,42)
        $script:Cmuted=[System.Drawing.Color]::FromArgb(71,85,105); $script:Caccent=[System.Drawing.Color]::FromArgb(2,132,199)
        $script:Cdanger=[System.Drawing.Color]::FromArgb(220,38,38); $script:Cgreen=[System.Drawing.Color]::FromArgb(22,163,74)
        $script:Cdisabled=[System.Drawing.Color]::FromArgb(226,232,240); $script:Cgrid=[System.Drawing.Color]::FromArgb(203,213,225)
    } else {
        $script:Cbg=[System.Drawing.Color]::FromArgb(15,23,42); $script:Ccard=[System.Drawing.Color]::FromArgb(30,41,59)
        $script:Ccard2=[System.Drawing.Color]::FromArgb(51,65,85); $script:Ctext=[System.Drawing.Color]::FromArgb(226,232,240)
        $script:Cmuted=[System.Drawing.Color]::FromArgb(148,163,184); $script:Caccent=[System.Drawing.Color]::FromArgb(14,165,233)
        $script:Cdanger=[System.Drawing.Color]::FromArgb(248,113,113); $script:Cgreen=[System.Drawing.Color]::FromArgb(74,222,128)
        $script:Cdisabled=[System.Drawing.Color]::FromArgb(71,85,105); $script:Cgrid=[System.Drawing.Color]::FromArgb(71,85,105)
    }
}
Set-Colors

$T_EN=@{Title='Batch File Renamer v4';Sub='Add files, build rules, preview, edit target names, then execute.';Mode='Mode';Copy='Copy template file';Rename='Rename selected files';Lang='Language';Theme='Theme';Template='Template file';Output='Output folder';BrowseFile='Browse file';BrowseFolder='Browse folder';Same='Same as template';Count='Output count';AddFiles='Add files';ClearFiles='Clear sources';Rules='Rule builder';Target='Target';Dir='Direction';Delim='Delimiter';SegNo='Segment No.';CharStart='Char Start';CharLen='Char Length';ValMode='Value Mode';Static='Static Value';SeqStart='Seq Start';Step='Step';Pad='Pad';ValList='Value list, one per line';AddRule='Add Rule';RemoveRule='Remove Rule';ClearRules='Clear Rules';Example='Live highlight example';Preview='Apply rules / preview';AsSource='Use source name as target';Editor='Open large editor';Execute='Execute OK rows';Export='Export CSV';Import='Import CSV';Folder='Selected row target folder';ApplySel='Apply to selected';ApplyAll='Apply to all';Ready='Ready.'}
$T_ZH=@{Title='批次檔名工具 v4';Sub='加入檔案、建立規則、預覽、手動修 target，最後才執行。不要讓檔名災難免費加班。';Mode='模式';Copy='複製模板檔';Rename='重新命名已選檔案';Lang='語言';Theme='主題';Template='模板檔案';Output='輸出資料夾';BrowseFile='選擇檔案';BrowseFolder='選擇資料夾';Same='同模板資料夾';Count='輸出數量';AddFiles='加入檔案';ClearFiles='清除來源';Rules='規則設定';Target='目標';Dir='方向';Delim='分隔符';SegNo='第幾段';CharStart='字元位置';CharLen='替換長度';ValMode='值模式';Static='固定值';SeqStart='起始';Step='間距';Pad='補零';ValList='值清單，一行一個';AddRule='新增規則';RemoveRule='刪除規則';ClearRules='清除規則';Example='即時標示範例';Preview='套用規則 / 預覽';AsSource='Target 套用原檔名';Editor='開啟大編輯視窗';Execute='執行 OK 列';Export='匯出 CSV';Import='匯入 CSV';Folder='選取列的目標資料夾';ApplySel='套用到選取';ApplyAll='套用到全部';Ready='就緒。'}
function TT($k){ if($script:Lang -eq 'ZH'){return $T_ZH[$k]} return $T_EN[$k] }

function L($text,$x,$y,$w,$h,$font=$FontNormal,$fore=$script:Ctext){$o=New-Object System.Windows.Forms.Label;$o.Text=$text;$o.Location=New-Object System.Drawing.Point($x,$y);$o.Size=New-Object System.Drawing.Size($w,$h);$o.Font=$font;$o.ForeColor=$fore;$o.BackColor=[System.Drawing.Color]::Transparent;return $o}
function B($text,$x,$y,$w,$h,$role='Normal'){$o=New-Object System.Windows.Forms.Button;$o.Text=$text;$o.Location=New-Object System.Drawing.Point($x,$y);$o.Size=New-Object System.Drawing.Size($w,$h);$o.FlatStyle='Flat';$o.FlatAppearance.BorderSize=0;$o.Font=$FontButton;$o.Cursor=[System.Windows.Forms.Cursors]::Hand;$o.Tag=$role;return $o}
function TB($text,$x,$y,$w,$h=26,$multi=$false){$o=New-Object System.Windows.Forms.TextBox;$o.Text=$text;$o.Location=New-Object System.Drawing.Point($x,$y);$o.Size=New-Object System.Drawing.Size($w,$h);$o.Font=$FontNormal;$o.BorderStyle='FixedSingle';if($multi){$o.Multiline=$true;$o.ScrollBars='Vertical';$o.AcceptsReturn=$true;$o.Font=$FontMono};return $o}
function CB($x,$y,$w,[string[]]$items){$o=New-Object System.Windows.Forms.ComboBox;$o.Location=New-Object System.Drawing.Point($x,$y);$o.Size=New-Object System.Drawing.Size($w,26);$o.DropDownStyle='DropDownList';$o.Font=$FontNormal;foreach($i in $items){[void]$o.Items.Add($i)};$o.SelectedIndex=0;return $o}
function NUM($x,$y,$w,$min,$max,$val){$o=New-Object System.Windows.Forms.NumericUpDown;$o.Location=New-Object System.Drawing.Point($x,$y);$o.Size=New-Object System.Drawing.Size($w,26);$o.Minimum=$min;$o.Maximum=$max;$o.Value=$val;return $o}
function Status($s){$status.Text=$s;[System.Windows.Forms.Application]::DoEvents()}

function ThemeButton($b){switch([string]$b.Tag){'Accent'{$b.BackColor=$script:Caccent;$b.ForeColor=[System.Drawing.Color]::White}'Danger'{$b.BackColor=$script:Cdanger;$b.ForeColor=[System.Drawing.Color]::White}'Green'{$b.BackColor=$script:Cgreen;$b.ForeColor=if($script:Theme -eq 'Light'){[System.Drawing.Color]::White}else{[System.Drawing.Color]::FromArgb(15,23,42)}}default{$b.BackColor=$script:Ccard2;$b.ForeColor=$script:Ctext}}}
function GridTheme($g,$showFolder=$false){$g.AllowUserToAddRows=$false;$g.AllowUserToDeleteRows=$true;$g.MultiSelect=$true;$g.SelectionMode='FullRowSelect';$g.RowHeadersVisible=$false;$g.BackgroundColor=$script:Ccard;$g.GridColor=$script:Cgrid;$g.DefaultCellStyle.BackColor=$script:Ccard;$g.DefaultCellStyle.ForeColor=$script:Ctext;$g.DefaultCellStyle.SelectionBackColor=$script:Caccent;$g.DefaultCellStyle.SelectionForeColor=[System.Drawing.Color]::White;$g.ColumnHeadersDefaultCellStyle.BackColor=$script:Ccard2;$g.ColumnHeadersDefaultCellStyle.ForeColor=$script:Ctext;$g.EnableHeadersVisualStyles=$false;$g.Font=$FontMono;if($g.Columns.Count -eq 0){[void]$g.Columns.Add('No','#');[void]$g.Columns.Add('Action','Action');[void]$g.Columns.Add('SourceName','Source name');[void]$g.Columns.Add('TargetName','Target name');[void]$g.Columns.Add('Status','Status');[void]$g.Columns.Add('SourcePath','SourcePath');[void]$g.Columns.Add('TargetFolder','Target folder')};$g.Columns['No'].Width=42;$g.Columns['Action'].Width=70;$g.Columns['SourceName'].Width=280;$g.Columns['TargetName'].Width=340;$g.Columns['Status'].Width=160;$g.Columns['SourcePath'].Visible=$false;$g.Columns['TargetFolder'].Visible=$showFolder;$g.Columns['TargetFolder'].Width=430;$g.Columns['TargetName'].ReadOnly=$false;foreach($c in @('No','Action','SourceName','Status','SourcePath')){$g.Columns[$c].ReadOnly=$true}}
function ApplyTheme($c){try{if($c -is [System.Windows.Forms.Form] -or $c -is [System.Windows.Forms.Panel] -or $c -is [System.Windows.Forms.GroupBox]){$c.BackColor=$script:Cbg;$c.ForeColor=$script:Ctext}elseif($c -is [System.Windows.Forms.Button]){ThemeButton $c}elseif($c -is [System.Windows.Forms.TextBox] -or $c -is [System.Windows.Forms.ComboBox] -or $c -is [System.Windows.Forms.NumericUpDown] -or $c -is [System.Windows.Forms.ListView] -or $c -is [System.Windows.Forms.RichTextBox]){$c.BackColor=$script:Ccard2;$c.ForeColor=$script:Ctext}elseif($c -is [System.Windows.Forms.Label] -or $c -is [System.Windows.Forms.RadioButton]){$c.ForeColor=$script:Ctext;$c.BackColor=[System.Drawing.Color]::Transparent}elseif($c -is [System.Windows.Forms.DataGridView]){GridTheme $c $c.Columns['TargetFolder'].Visible}}catch{};foreach($ch in $c.Controls){ApplyTheme $ch}}
function EnableVisual($c,$en){$c.Enabled=$en;if($en){$c.BackColor=$script:Ccard2;$c.ForeColor=$script:Ctext}else{$c.BackColor=$script:Cdisabled;$c.ForeColor=$script:Cmuted}}

function SingleFile($title){$d=New-Object System.Windows.Forms.OpenFileDialog;$d.Title=$title;$d.Filter='All files (*.*)|*.*';$d.Multiselect=$false;if($d.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK){return [string]$d.FileName};return ''}
function MultiFiles($title){$d=New-Object System.Windows.Forms.OpenFileDialog;$d.Title=$title;$d.Filter='All files (*.*)|*.*';$d.Multiselect=$true;if($d.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK){return @($d.FileNames)};return @()}
function FolderPick($title,$initial=''){$d=New-Object System.Windows.Forms.OpenFileDialog;$d.Title=$title;$d.ValidateNames=$false;$d.CheckFileExists=$false;$d.CheckPathExists=$true;$d.FileName='Select this folder';if($initial -and (Test-Path $initial)){$d.InitialDirectory=$initial};if($d.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK){return [System.IO.Path]::GetDirectoryName($d.FileName)};return $null}

function Values(){if($null -eq $txtList.Text){return @()};$r=$txtList.Text -split "`r?`n",-1;if($r.Count -gt 0 -and $r[$r.Count-1] -eq ''){$r=$r[0..($r.Count-2)]};return @($r)}
function CleanPart($s){$r=[string]$s;foreach($ch in [System.IO.Path]::GetInvalidFileNameChars()){$r=$r.Replace($ch,'_')};return $r}
function RuleValue($rule,$i,$lines){if($rule.ValueMode -eq 'Delete'){return ''};if($rule.ValueMode -eq 'Static'){return [string]$rule.StaticValue};if($rule.ValueMode -eq 'List'){if($i -ge $lines.Count){throw "Value list missing row $($i+1)"};return [string]$lines[$i]};if($rule.ValueMode -eq 'SeqUp'){$v=[int]$rule.SeqStart+([int]$rule.SeqStep*$i)}else{$v=[int]$rule.SeqStart-([int]$rule.SeqStep*$i)};if([int]$rule.Pad -gt 0){return $v.ToString('D'+[int]$rule.Pad)};return $v.ToString()}
function ApplyRules($path,$i,$lines){$base=[System.IO.Path]::GetFileNameWithoutExtension($path);$ext=[System.IO.Path]::GetExtension($path);foreach($r in $script:Rules){$val=CleanPart (RuleValue $r $i $lines);if($r.Target -eq 'Segment'){$del=[string]$r.Delimiter;if([string]::IsNullOrEmpty($del)){throw 'Delimiter cannot be empty'};$parts=@($base -split [regex]::Escape($del),-1);$seg=[int]$r.SegmentNo;if($seg -lt 1 -or $seg -gt $parts.Count){throw "Segment $seg out of range. Parts=$($parts.Count)"};if($r.FromEnd){$idx=$parts.Count-$seg}else{$idx=$seg-1};if($r.ValueMode -eq 'Delete'){$new=@();for($p=0;$p -lt $parts.Count;$p++){if($p -ne $idx){$new+=$parts[$p]}};$base=($new -join $del)}else{$parts[$idx]=$val;$base=($parts -join $del)}}else{$st=[int]$r.CharStart;$ln=[int]$r.CharLength;if($st -lt 1){throw 'Char start must be >= 1'};if($st -gt $base.Length+1){throw "Char start $st beyond length $($base.Length)"};$z=$st-1;if($ln -lt 0){throw 'Char length cannot be negative'};if($z+$ln -gt $base.Length){$ln=$base.Length-$z};$left=$base.Substring(0,$z);$right='';if($z+$ln -lt $base.Length){$right=$base.Substring($z+$ln)};if($r.ValueMode -eq 'Delete'){$val=''};$base=$left+$val+$right}};return $base+$ext}

function GV($row,$name){return [string]$row.Cells[$name].Value}
function SV($row,$name,$val){$row.Cells[$name].Value=[string]$val}
function AddRow($act,$src,$tgt,$folder,$st){$idx=$grid.Rows.Add();$r=$grid.Rows[$idx];SV $r 'No' ($idx+1);SV $r 'Action' $act;SV $r 'SourceName' ([System.IO.Path]::GetFileName($src));SV $r 'TargetName' $tgt;SV $r 'Status' $st;SV $r 'SourcePath' $src;SV $r 'TargetFolder' $folder}
function TempRow($list,$act,$src,$tgt,$folder,$st){$list.Add([pscustomobject]@{Action=$act;SourcePath=$src;TargetName=$tgt;TargetFolder=$folder;Status=$st})}
function LoadRows($list){$grid.Rows.Clear();foreach($r in $list){AddRow $r.Action $r.SourcePath $r.TargetName $r.TargetFolder $r.Status}}
function TargetPath($row){$folder=GV $row 'TargetFolder';$name=GV $row 'TargetName';if([string]::IsNullOrWhiteSpace($folder)){throw 'Target folder empty'};if([string]::IsNullOrWhiteSpace($name)){throw 'Target name empty'};return Join-Path $folder $name}
function Reindex(){for($i=0;$i -lt $grid.Rows.Count;$i++){if(-not $grid.Rows[$i].IsNewRow){SV $grid.Rows[$i] 'No' ($i+1)}}}
function CheckRows(){$seen=@{};foreach($r in $grid.Rows){if($r.IsNewRow){continue};$st='OK';try{$src=GV $r 'SourcePath';$tp=TargetPath $r;$tn=GV $r 'TargetName';if([string]::IsNullOrWhiteSpace($tn)){$st='Target name empty'}elseif($tn.IndexOfAny([System.IO.Path]::GetInvalidFileNameChars()) -ge 0){$st='Invalid filename'}elseif((GV $r 'Action') -eq 'Rename' -and -not(Test-Path $src)){$st='Source missing'}elseif((GV $r 'Action') -eq 'Rename' -and $src.ToLower() -eq $tp.ToLower()){$st='No change'}elseif(Test-Path $tp){$st='Target exists'}elseif($seen.ContainsKey($tp.ToLower())){$st='Duplicate target'}else{$seen[$tp.ToLower()]=$true}}catch{$st='Error: '+$_.Exception.Message};SV $r 'Status' $st}}
function AddSources($files){foreach($f in $files){if($f -and (Test-Path $f)){if(-not $script:Sources.Contains($f)){$script:Sources.Add($f)};AddRow 'Rename' $f ([System.IO.Path]::GetFileName($f)) ([System.IO.Path]::GetDirectoryName($f)) 'Source loaded'}};CheckRows;Status "Source files loaded: $($script:Sources.Count)";UpdateExample}
function BuildRulesPreview(){$lines=Values;$usesList=$false;foreach($r in $script:Rules){if($r.ValueMode -eq 'List'){$usesList=$true}};if($script:Rules.Count -eq 0){[System.Windows.Forms.MessageBox]::Show('No rules yet. Existing preview is kept.','Warning','OK','Warning')|Out-Null;return};$tmp=New-Object System.Collections.Generic.List[object];if($rbCopy.Checked){$tpl=$txtTemplate.Text.Trim();$out=$txtOutput.Text.Trim();if(-not(Test-Path $tpl)){[System.Windows.Forms.MessageBox]::Show('Template file does not exist. Select again.','Warning','OK','Warning')|Out-Null;return};if(-not(Test-Path $out)){[System.Windows.Forms.MessageBox]::Show('Output folder does not exist.','Warning','OK','Warning')|Out-Null;return};$cnt=[int]$numCount.Value;if($usesList){if($lines.Count -eq 0){[System.Windows.Forms.MessageBox]::Show('A rule uses Value List, but value list is empty. Existing preview is kept.','Warning','OK','Warning')|Out-Null;return};$cnt=$lines.Count};for($i=0;$i -lt $cnt;$i++){try{$t=ApplyRules $tpl $i $lines;TempRow $tmp 'Copy' $tpl $t $out 'OK'}catch{TempRow $tmp 'Copy' $tpl ([System.IO.Path]::GetFileName($tpl)) $out ('Error: '+$_.Exception.Message)}}}else{if($script:Sources.Count -eq 0){[System.Windows.Forms.MessageBox]::Show('Add source files first. Existing preview is kept.','Warning','OK','Warning')|Out-Null;return};if($usesList -and $lines.Count -ne $script:Sources.Count){[System.Windows.Forms.MessageBox]::Show("Value List row count does not match file count.`nValue lines: $($lines.Count)`nFiles: $($script:Sources.Count)`nExisting preview is kept.",'Value List mismatch','OK','Warning')|Out-Null;return};for($i=0;$i -lt $script:Sources.Count;$i++){$s=$script:Sources[$i];$folder=[System.IO.Path]::GetDirectoryName($s);try{$t=ApplyRules $s $i $lines;TempRow $tmp 'Rename' $s $t $folder 'OK'}catch{TempRow $tmp 'Rename' $s ([System.IO.Path]::GetFileName($s)) $folder ('Error: '+$_.Exception.Message)}}};LoadRows $tmp;CheckRows;Status "Preview generated: $($grid.Rows.Count) row(s). TargetName is editable."}
function RebuildRules(){$ruleList.Items.Clear();$i=1;foreach($r in $script:Rules){$where=if($r.Target -eq 'Segment'){"Delim '$($r.Delimiter)', Seg $($r.SegmentNo), "+$(if($r.FromEnd){'from end'}else{'from start'})}else{"Char $($r.CharStart), Len $($r.CharLength)"};$val=switch($r.ValueMode){'Static'{'Static:['+$r.StaticValue+']'}'List'{'Value list'}'SeqUp'{"Seq+ start=$($r.SeqStart), step=$($r.SeqStep), pad=$($r.Pad)"}'SeqDown'{"Seq- start=$($r.SeqStart), step=$($r.SeqStep), pad=$($r.Pad)"}'Delete'{'Delete'}};$it=New-Object System.Windows.Forms.ListViewItem($i.ToString());[void]$it.SubItems.Add($r.Target);[void]$it.SubItems.Add($where);[void]$it.SubItems.Add($val);[void]$ruleList.Items.Add($it);$i++}}
function GetSample(){if($grid.SelectedRows.Count -gt 0){$n=GV $grid.SelectedRows[0] 'SourceName';if($n){return $n}};if(Test-Path $txtTemplate.Text){return [System.IO.Path]::GetFileName($txtTemplate.Text)};if($grid.Rows.Count -gt 0){$n=GV $grid.Rows[0] 'SourceName';if($n){return $n}};return '50-INDS-AT-52602_0.pdf'}
function UpdateExample(){if($null -eq $rtExample){return};$base=[System.IO.Path]::GetFileNameWithoutExtension((GetSample));$rtExample.Clear();$rtExample.Text=$base;$rtExample.SelectAll();$rtExample.SelectionBackColor=$rtExample.BackColor;$rtExample.SelectionColor=$script:Ctext;try{if([string]$cmbTarget.SelectedItem -eq 'Segment'){$del=$txtDelim.Text;if([string]::IsNullOrEmpty($del)){return};$parts=@($base -split [regex]::Escape($del),-1);$seg=[int]$numSeg.Value;if($seg -lt 1 -or $seg -gt $parts.Count){return};if([string]$cmbDir.SelectedItem -eq 'FromEnd'){$target=$parts.Count-$seg}else{$target=$seg-1};$pos=0;for($i=0;$i -lt $parts.Count;$i++){$len=$parts[$i].Length;if($i -eq $target){$rtExample.Select($pos,[Math]::Max(1,$len));$rtExample.SelectionBackColor=[System.Drawing.Color]::Gold;$rtExample.SelectionColor=[System.Drawing.Color]::Black;break};$pos+=$len+$del.Length}}else{$st=[int]$numCharStart.Value;$ln=[int]$numCharLen.Value;if($st -lt 1 -or $st -gt $base.Length+1){return};$z=$st-1;if($ln -le 0){$ln=1};if($z+$ln -gt $base.Length){$ln=$base.Length-$z};if($ln -le 0){return};$rtExample.Select($z,$ln);$rtExample.SelectionBackColor=[System.Drawing.Color]::Gold;$rtExample.SelectionColor=[System.Drawing.Color]::Black}}catch{};$rtExample.Select(0,0)}
function UpdateValueMode(){ $m=[string]$cmbValMode.SelectedItem; EnableVisual $txtStatic ($m -eq 'Static'); EnableVisual $txtList ($m -eq 'List'); $seq=($m -eq 'SeqUp' -or $m -eq 'SeqDown'); EnableVisual $numStart $seq; EnableVisual $numStep $seq; EnableVisual $numPad $seq; UpdateExample }
function SyncGrid($from,$to){$to.Rows.Clear();foreach($r in $from.Rows){if($r.IsNewRow){continue};$idx=$to.Rows.Add();$nr=$to.Rows[$idx];foreach($c in @('No','Action','SourceName','TargetName','Status','SourcePath','TargetFolder')){$nr.Cells[$c].Value=[string]$r.Cells[$c].Value}}}
function OpenEditor(){$ed=New-Object System.Windows.Forms.Form;$ed.Text='Large preview editor';$ed.Size=New-Object System.Drawing.Size(1180,650);$ed.StartPosition='CenterScreen';$ed.BackColor=$script:Cbg;$eg=New-Object System.Windows.Forms.DataGridView;$eg.Location=New-Object System.Drawing.Point(16,44);$eg.Size=New-Object System.Drawing.Size(1125,500);$eg.Anchor='Top,Bottom,Left,Right';GridTheme $eg $true;SyncGrid $grid $eg;$ed.Controls.Add((L 'Non-modal editor. Main window remains editable. Click Apply to copy changes back.' 16 12 980 24 $FontSub $script:Cmuted));$ed.Controls.Add($eg);$ba=B 'Apply changes' 16 558 130 34 'Green';$bc=B 'Close' 160 558 90 34 'Normal';$ed.Controls.Add($ba);$ed.Controls.Add($bc);ApplyTheme $ed;$ba.add_Click({$eg.EndEdit();SyncGrid $eg $grid;Reindex;CheckRows;Status 'Large editor changes applied.'});$bc.add_Click({$ed.Close()});$ed.Show($form)}
function ExportCSV(){if($grid.Rows.Count -eq 0){Status 'No preview to export.';return};$rows=@();foreach($r in $grid.Rows){if($r.IsNewRow){continue};$tp='';try{$tp=TargetPath $r}catch{};$rows+=[pscustomobject]@{Action=GV $r 'Action';SourceName=GV $r 'SourceName';TargetName=GV $r 'TargetName';Status=GV $r 'Status';SourcePath=GV $r 'SourcePath';TargetFolder=GV $r 'TargetFolder';TargetPath=$tp}};$d=New-Object System.Windows.Forms.SaveFileDialog;$d.Filter='CSV files (*.csv)|*.csv';$d.FileName='rename_preview.csv';if($d.ShowDialog() -eq 'OK'){try{$rows|Export-Csv -Path $d.FileName -NoTypeInformation -Encoding UTF8;Status 'Exported CSV.'}catch{Status ('Export failed: '+$_.Exception.Message)}}}
function ImportCSV(){$d=New-Object System.Windows.Forms.OpenFileDialog;$d.Title='Import preview CSV';$d.Filter='CSV files (*.csv)|*.csv|All files (*.*)|*.*';if($d.ShowDialog() -ne 'OK'){return};try{$rows=@(Import-Csv -Path $d.FileName);if($rows.Count -eq 0){Status 'CSV is empty.';return};$ans=[System.Windows.Forms.MessageBox]::Show('Clear current preview before importing?','Import CSV','YesNoCancel','Question');if($ans -eq 'Cancel'){return};if($ans -eq 'Yes'){$grid.Rows.Clear();$script:Sources.Clear()};foreach($r in $rows){$act=if($r.Action){[string]$r.Action}else{'Rename'};$src=[string]$r.SourcePath;$tn=[string]$r.TargetName;$tf=[string]$r.TargetFolder;if(-not $tn -and $r.TargetPath){$tn=[System.IO.Path]::GetFileName([string]$r.TargetPath)};if(-not $tf -and $r.TargetPath){$tf=[System.IO.Path]::GetDirectoryName([string]$r.TargetPath)};if(-not $tf -and $src){$tf=[System.IO.Path]::GetDirectoryName($src)};if(-not $tn -and $src){$tn=[System.IO.Path]::GetFileName($src)};if($src -and -not $script:Sources.Contains($src)){$script:Sources.Add($src)};AddRow $act $src $tn $tf 'Imported'};CheckRows;Status "Imported CSV rows: $($rows.Count)"}catch{Status ('Import failed: '+$_.Exception.Message)}}
function ExecuteOK(){$grid.EndEdit();CheckRows;$ok=@();foreach($r in $grid.Rows){if($r.IsNewRow){continue};if((GV $r 'Status') -eq 'OK'){$ok+=$r}};if($ok.Count -eq 0){Status 'No OK rows to execute.';return};$ans=[System.Windows.Forms.MessageBox]::Show("Execute $($ok.Count) OK row(s)? Warning/error rows are skipped.",'Confirm','YesNo','Warning');if($ans -ne 'Yes'){return};$done=0;$fail=0;foreach($r in $ok){try{$src=GV $r 'SourcePath';$tp=TargetPath $r;if((GV $r 'Action') -eq 'Copy'){Copy-Item -LiteralPath $src -Destination $tp -ErrorAction Stop}else{Rename-Item -LiteralPath $src -NewName ([System.IO.Path]::GetFileName($tp)) -ErrorAction Stop};$done++}catch{$fail++}};Status "Execution done. Success: $done, Failed: $fail";CheckRows}
function UpdateLang(){$lblTitle.Text=TT 'Title';$lblSub.Text=TT 'Sub';$grpMode.Text=TT 'Mode';$rbCopy.Text=TT 'Copy';$rbRename.Text=TT 'Rename';$grpSettings.Text=TT 'Settings';$lblLang.Text=TT 'Lang';$lblTheme.Text=TT 'Theme';$lblTemplate.Text=TT 'Template';$lblOutput.Text=TT 'Output';$btnTemplate.Text=TT 'BrowseFile';$btnOutput.Text=TT 'BrowseFolder';$btnSame.Text=TT 'Same';$lblCount.Text=TT 'Count';$btnAddFiles.Text=TT 'AddFiles';$btnClearFiles.Text=TT 'ClearFiles';$grpRules.Text=TT 'Rules';$lblTarget.Text=TT 'Target';$lblDir.Text=TT 'Dir';$lblDelim.Text=TT 'Delim';$lblSeg.Text=TT 'SegNo';$lblCharStart.Text=TT 'CharStart';$lblCharLen.Text=TT 'CharLen';$lblValMode.Text=TT 'ValMode';$lblStatic.Text=TT 'Static';$lblSeqStart.Text=TT 'SeqStart';$lblStep.Text=TT 'Step';$lblPad.Text=TT 'Pad';$lblList.Text=TT 'ValList';$btnAddRule.Text=TT 'AddRule';$btnRemoveRule.Text=TT 'RemoveRule';$btnClearRules.Text=TT 'ClearRules';$lblExample.Text=TT 'Example';$btnPreview.Text=TT 'Preview';$btnAsSource.Text=TT 'AsSource';$btnEditor.Text=TT 'Editor';$btnExecute.Text=TT 'Execute';$btnExport.Text=TT 'Export';$btnImport.Text=TT 'Import';$lblFolder.Text=TT 'Folder';$btnBrowseFolder.Text=TT 'Browse';$btnApplySel.Text=TT 'ApplySel';$btnApplyAll.Text=TT 'ApplyAll';Status (TT 'Ready')}

# ---------- Form ----------
$form=New-Object System.Windows.Forms.Form;$form.Text='Batch File Renamer v4';$form.Size=New-Object System.Drawing.Size(1240,820);$form.MinimumSize=New-Object System.Drawing.Size(1080,720);$form.StartPosition='CenterScreen';$form.AutoScaleMode=[System.Windows.Forms.AutoScaleMode]::Dpi
$lblTitle=L '' 18 12 430 32 $FontTitle;$lblSub=L '' 20 44 830 20 $FontSub $script:Cmuted;$form.Controls.Add($lblTitle);$form.Controls.Add($lblSub)
$btnHelp=B '?' 1140 16 42 34 'Accent';$btnHelp.Anchor='Top,Right';$form.Controls.Add($btnHelp)
$grpSettings=New-Object System.Windows.Forms.GroupBox;$grpSettings.Location=New-Object System.Drawing.Point(845,70);$grpSettings.Size=New-Object System.Drawing.Size(335,78);$grpSettings.Anchor='Top,Right';$form.Controls.Add($grpSettings)
$lblLang=L '' 14 22 75 20 $FontSub;$cmbLang=CB 14 44 115 @('English','中文');$cmbLang.SelectedIndex=1;$lblTheme=L '' 160 22 65 20 $FontSub;$cmbTheme=CB 160 44 115 @('Dark','Light');$grpSettings.Controls.AddRange(@($lblLang,$cmbLang,$lblTheme,$cmbTheme))
$grpMode=New-Object System.Windows.Forms.GroupBox;$grpMode.Location=New-Object System.Drawing.Point(20,72);$grpMode.Size=New-Object System.Drawing.Size(360,76);$form.Controls.Add($grpMode)
$rbCopy=New-Object System.Windows.Forms.RadioButton;$rbCopy.Location=New-Object System.Drawing.Point(16,30);$rbCopy.AutoSize=$true;$rbRename=New-Object System.Windows.Forms.RadioButton;$rbRename.Location=New-Object System.Drawing.Point(180,30);$rbRename.AutoSize=$true;$rbRename.Checked=$true;$grpMode.Controls.AddRange(@($rbCopy,$rbRename))
$panelCopy=New-Object System.Windows.Forms.Panel;$panelCopy.Location=New-Object System.Drawing.Point(400,72);$panelCopy.Size=New-Object System.Drawing.Size(430,110);$form.Controls.Add($panelCopy)
$lblTemplate=L '' 0 0 110 20 $FontSub;$txtTemplate=TB '' 0 22 290;$btnTemplate=B '' 300 20 115 28;$lblOutput=L '' 0 55 110 20 $FontSub;$txtOutput=TB '' 0 77 240;$btnOutput=B '' 250 75 100 28;$btnSame=B '' 360 75 55 28;$panelCopy.Controls.AddRange(@($lblTemplate,$txtTemplate,$btnTemplate,$lblOutput,$txtOutput,$btnOutput,$btnSame))
$lblCount=L '' 400 158 100 20 $FontSub;$numCount=NUM 400 180 90 1 10000 10;$form.Controls.AddRange(@($lblCount,$numCount))
$btnAddFiles=B '' 20 165 110 34 'Accent';$btnClearFiles=B '' 145 165 120 34;$form.Controls.AddRange(@($btnAddFiles,$btnClearFiles))
$grpRules=New-Object System.Windows.Forms.GroupBox;$grpRules.Location=New-Object System.Drawing.Point(20,212);$grpRules.Size=New-Object System.Drawing.Size(1160,220);$grpRules.Anchor='Top,Left,Right';$form.Controls.Add($grpRules)
$lblTarget=L '' 14 25 70 20 $FontSub;$cmbTarget=CB 14 47 105 @('Segment','Character');$lblDir=L '' 132 25 80 20 $FontSub;$cmbDir=CB 132 47 110 @('FromStart','FromEnd');$lblDelim=L '' 255 25 80 20 $FontSub;$txtDelim=TB '-' 255 47 60;$lblSeg=L '' 330 25 95 20 $FontSub;$numSeg=NUM 330 47 70 1 50 4;$lblCharStart=L '' 415 25 85 20 $FontSub;$numCharStart=NUM 415 47 70 1 500 1;$lblCharLen=L '' 500 25 90 20 $FontSub;$numCharLen=NUM 500 47 70 0 500 1;$lblValMode=L '' 590 25 90 20 $FontSub;$cmbValMode=CB 590 47 115 @('Static','List','SeqUp','SeqDown','Delete');$lblStatic=L '' 720 25 105 20 $FontSub;$txtStatic=TB '' 720 47 140;$lblSeqStart=L '' 875 25 75 20 $FontSub;$numStart=NUM 875 47 70 -999999 999999 1;$lblStep=L '' 958 25 50 20 $FontSub;$numStep=NUM 958 47 60 1 999999 1;$lblPad=L '' 1030 25 45 20 $FontSub;$numPad=NUM 1030 47 55 0 20 0;$btnAddRule=B '' 1095 45 60 30 'Accent'
$grpRules.Controls.AddRange(@($lblTarget,$cmbTarget,$lblDir,$cmbDir,$lblDelim,$txtDelim,$lblSeg,$numSeg,$lblCharStart,$numCharStart,$lblCharLen,$numCharLen,$lblValMode,$cmbValMode,$lblStatic,$txtStatic,$lblSeqStart,$numStart,$lblStep,$numStep,$lblPad,$numPad,$btnAddRule))
$ruleList=New-Object System.Windows.Forms.ListView;$ruleList.Location=New-Object System.Drawing.Point(14,88);$ruleList.Size=New-Object System.Drawing.Size(645,112);$ruleList.View='Details';$ruleList.FullRowSelect=$true;$ruleList.GridLines=$true;$ruleList.Font=$FontMono;[void]$ruleList.Columns.Add('#',35);[void]$ruleList.Columns.Add('Target',80);[void]$ruleList.Columns.Add('Where',260);[void]$ruleList.Columns.Add('Value',250)
$btnRemoveRule=B '' 675 92 118 30 'Danger';$btnClearRules=B '' 675 132 118 30;$lblList=L '' 810 90 220 20 $FontSub;$txtList=TB '' 810 112 160 80 $true;$lblExample=L '' 990 90 160 20 $FontSub;$rtExample=New-Object System.Windows.Forms.RichTextBox;$rtExample.Location=New-Object System.Drawing.Point(990,112);$rtExample.Size=New-Object System.Drawing.Size(155,80);$rtExample.ReadOnly=$true;$rtExample.BorderStyle='FixedSingle';$rtExample.Font=$FontMono
$grpRules.Controls.AddRange(@($ruleList,$btnRemoveRule,$btnClearRules,$lblList,$txtList,$lblExample,$rtExample))
$btnPreview=B '' 20 445 155 34 'Accent';$btnAsSource=B '' 185 445 175 34;$btnEditor=B '' 370 445 150 34;$btnExecute=B '' 530 445 135 34 'Green';$btnExport=B '' 675 445 105 34;$btnImport=B '' 790 445 105 34;$form.Controls.AddRange(@($btnPreview,$btnAsSource,$btnEditor,$btnExecute,$btnExport,$btnImport))
$lblFolder=L '' 915 440 230 20 $FontSub;$lblFolder.Anchor='Top,Right';$txtFolder=TB '' 915 462 180;$txtFolder.Anchor='Top,Right';$btnBrowseFolder=B '' 1105 460 75 28;$btnBrowseFolder.Anchor='Top,Right';$btnApplySel=B '' 915 494 128 28;$btnApplySel.Anchor='Top,Right';$btnApplyAll=B '' 1052 494 128 28;$btnApplyAll.Anchor='Top,Right';$form.Controls.AddRange(@($lblFolder,$txtFolder,$btnBrowseFolder,$btnApplySel,$btnApplyAll))
$grid=New-Object System.Windows.Forms.DataGridView;$grid.Location=New-Object System.Drawing.Point(20,535);$grid.Size=New-Object System.Drawing.Size(1160,205);$grid.Anchor='Top,Bottom,Left,Right';$form.Controls.Add($grid);GridTheme $grid $false
$status=L 'Ready.' 20 755 1120 24 $FontSub $script:Cmuted;$status.Anchor='Bottom,Left,Right';$form.Controls.Add($status)

# events
$cmbLang.add_SelectedIndexChanged({if($cmbLang.SelectedIndex -eq 1){$script:Lang='ZH'}else{$script:Lang='EN'};UpdateLang})
$cmbTheme.add_SelectedIndexChanged({if($cmbTheme.SelectedIndex -eq 1){$script:Theme='Light'}else{$script:Theme='Dark'};Set-Colors;ApplyTheme $form;GridTheme $grid $false;UpdateValueMode;UpdateExample;Status 'Theme changed.'})
$rbCopy.add_CheckedChanged({$panelCopy.Visible=$rbCopy.Checked;$lblCount.Visible=$rbCopy.Checked;$numCount.Visible=$rbCopy.Checked;$btnAddFiles.Enabled=-not $rbCopy.Checked;$btnClearFiles.Enabled=-not $rbCopy.Checked})
$rbRename.add_CheckedChanged({$panelCopy.Visible=-not $rbRename.Checked;$lblCount.Visible=-not $rbRename.Checked;$numCount.Visible=-not $rbRename.Checked;$btnAddFiles.Enabled=$rbRename.Checked;$btnClearFiles.Enabled=$rbRename.Checked})
$btnTemplate.add_Click({$f=SingleFile 'Select template file';if($f){$txtTemplate.Text=$f;if([string]::IsNullOrWhiteSpace($txtOutput.Text)){$txtOutput.Text=[System.IO.Path]::GetDirectoryName($f)};Status ('Template selected: '+[System.IO.Path]::GetFileName($f));UpdateExample}})
$btnOutput.add_Click({$init=$txtOutput.Text;if(-not $init -and (Test-Path $txtTemplate.Text)){$init=[System.IO.Path]::GetDirectoryName($txtTemplate.Text)};$fol=FolderPick 'Select output folder' $init;if($fol){$txtOutput.Text=$fol}})
$btnSame.add_Click({if(Test-Path $txtTemplate.Text){$txtOutput.Text=[System.IO.Path]::GetDirectoryName($txtTemplate.Text)}})
$btnAddFiles.add_Click({AddSources (MultiFiles 'Select source files')})
$btnClearFiles.add_Click({$script:Sources.Clear();$grid.Rows.Clear();Status 'Source files cleared.';UpdateExample})
$btnAddRule.add_Click({$r=[pscustomobject]@{Target=[string]$cmbTarget.SelectedItem;FromEnd=([string]$cmbDir.SelectedItem -eq 'FromEnd');Delimiter=$txtDelim.Text;SegmentNo=[int]$numSeg.Value;CharStart=[int]$numCharStart.Value;CharLength=[int]$numCharLen.Value;ValueMode=[string]$cmbValMode.SelectedItem;StaticValue=$txtStatic.Text;SeqStart=[int]$numStart.Value;SeqStep=[int]$numStep.Value;Pad=[int]$numPad.Value};$script:Rules.Add($r);RebuildRules;Status "Rule added. Total rules: $($script:Rules.Count)"})
$btnRemoveRule.add_Click({if($ruleList.SelectedItems.Count -gt 0){$script:Rules.RemoveAt($ruleList.SelectedItems[0].Index);RebuildRules;Status 'Rule removed.'}})
$btnClearRules.add_Click({$script:Rules.Clear();RebuildRules;Status 'Rules cleared.'})
$btnPreview.add_Click({BuildRulesPreview})
$btnAsSource.add_Click({foreach($r in $grid.Rows){if(-not $r.IsNewRow){SV $r 'TargetName' (GV $r 'SourceName')}};CheckRows;Status 'Target names reset to source names.'})
$btnEditor.add_Click({OpenEditor})
$btnExecute.add_Click({ExecuteOK})
$btnExport.add_Click({ExportCSV})
$btnImport.add_Click({ImportCSV})
$grid.add_SelectionChanged({if($grid.SelectedRows.Count -gt 0){$txtFolder.Text=GV $grid.SelectedRows[0] 'TargetFolder';UpdateExample}})
$grid.add_CellEndEdit({CheckRows})
$grid.add_RowsRemoved({Reindex;CheckRows})
$btnBrowseFolder.add_Click({$f=FolderPick 'Select target folder' $txtFolder.Text;if($f){$txtFolder.Text=$f}})
$btnApplySel.add_Click({$f=$txtFolder.Text;if(-not(Test-Path $f)){Status 'Target folder does not exist.';return};foreach($r in $grid.SelectedRows){SV $r 'TargetFolder' $f};CheckRows;Status 'Target folder applied to selected rows.'})
$btnApplyAll.add_Click({$f=$txtFolder.Text;if(-not(Test-Path $f)){Status 'Target folder does not exist.';return};foreach($r in $grid.Rows){if(-not $r.IsNewRow){SV $r 'TargetFolder' $f}};CheckRows;Status 'Target folder applied to all rows.'})
foreach($c in @($cmbTarget,$cmbDir,$txtDelim,$numSeg,$numCharStart,$numCharLen,$cmbValMode,$txtStatic,$numStart,$numStep,$numPad)) { try{$c.add_TextChanged({UpdateExample});$c.add_ValueChanged({UpdateExample});$c.add_SelectedIndexChanged({UpdateExample})}catch{} }
$cmbValMode.add_SelectedIndexChanged({UpdateValueMode})
$btnHelp.add_Click({[System.Windows.Forms.MessageBox]::Show("基本流程：`n1. Rename 模式先加入檔案，檔案會直接出現在 preview。`n2. 新增規則，可用段落/字元、固定值/List/遞增/遞減/刪除。`n3. 套用規則後 TargetName 可手動改。`n4. 大編輯視窗是非強制視窗，主視窗仍可編輯。`n5. 匯出 CSV 後可手動改，再匯入。`n`nValue List：一行對一個檔案，行數不符不會清掉既有 preview。`nDelete：段落會刪整段；字元會刪指定範圍。`nFromEnd：倒數第幾段。`nStatic 空格會保留，不會 trim。",'How to use','OK','Information')|Out-Null})
$form.add_Resize({$grid.Height=[Math]::Max(150,$form.ClientSize.Height-$grid.Top-45);$grid.Width=[Math]::Max(900,$form.ClientSize.Width-40)})

# initial
$panelCopy.Visible=$false;$lblCount.Visible=$false;$numCount.Visible=$false
UpdateLang;ApplyTheme $form;GridTheme $grid $false;UpdateValueMode;UpdateExample;Status (TT 'Ready')
[void][System.Windows.Forms.Application]::Run($form)
